

LOAD DATA INFILE 'fakeUsers.csv'
INTO TABLE Users
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n';

LOAD DATA INFILE 'fakeStatuses.csv'
INTO TABLE Statuses
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n';

LOAD DATA INFILE 'fakeProfile.csv'
INTO TABLE `Profile`
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n';

LOAD DATA INFILE 'fakeBuisness.csv'
INTO TABLE Buisness
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n';

LOAD DATA INFILE 'fakeListing.csv'
INTO TABLE Listing
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n';

LOAD DATA INFILE 'fakeMessages.csv'
INTO TABLE Messages
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n';
